Simplify installer and leverage dot_vim install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,69 +1,25 @@
 #!/usr/bin/env bash
 
 DOTFILES="dansomething/dotfiles"
-DOTVIM="https://github.com/dansomething/dot_vim.git"
-VUNDLE="http://github.com/gmarik/vundle.git"
+CMDS="git vim"
 
-# Detect the OS platform
-unamestr=$(uname)
-case "$unamestr" in
-    Darwin) PLATFORM='osx' ;;
-    Linux) PLATFORM='linux' ;;
-    *) PLATFORM='windows' ;;
-esac
-unset unamestr
-
-if [[ "$PLATFORM" == 'osx' ]]; then
-  # Check for Homebrew
-  if test ! $(which brew); then
-    echo " Installing Homebrew"
-    ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
-
-    if test ! $(which git); then
-      echo " Installing git"
-      brew install git
-    fi
-  else
-    echo " + Homebrew found."
-  fi
-fi
-
-# Check for required commands...
-# TODO Remove the dependency on gem
-CMDS="gem git vim"
+# Check for necessary commands
 for cmd in $CMDS; do
-    type -P $cmd &>/dev/null && continue || { echo "$cmd command not found. Please install $cmd."; exit 1; }
-done
-
-# TODO Remove the dependency on rake
-# Install required gems...
-GEMS="rake json"
-for gem in $GEMS; do
-    found=`gem list $gem | grep -i $gem`
-    if [ "$found" != "" ]; then
-        parts=( $found )
-        echo "Found ${parts[0]} ${parts[1]}"
-        continue
-    fi
-
-    echo "---------------------------"
-    echo "Installing $gem"
-    sudo gem install $gem
-    echo "---------------------------"
+  hash $cmd >/dev/null 2>&1 && {
+    echo "$cmd command not found. Please install $cmd."
+    exit 1
+  }
 done
 
 # Install Homeshick
-echo "Installing Homeshick..."
+echo "Installing Homeshick to manage dotfiles..."
 git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
-ln -s $HOME/.homesick/repos/homeshick/home/.homeshick $HOME/.homeshick
+source "$HOME/.homesick/repos/homeshick/homeshick.sh"
 
 # Install dotfiles
-~/.homeshick clone $DOTFILES
-~/.homeshick symlink dotfiles
+homeshick clone $DOTFILES
+homeshick symlink dotfiles
 
 # Install dot_vim + vundle
-# .vim should be pulled as a submodule of the dotfiles
-cd ~/.vim
-git clone $VUNDLE bundle/vundle
-rake vim:link
-vim +BundleInstall +qall
+cd $HOME/.vim
+./install
